// Auto-generated by lithe-cli - do not edit manually

#[path = "../src/pages/index.rs"]
pub mod pages_index;

#[path = "../src/pages/contact.rs"]
pub mod pages_contact;

#[path = "../src/pages/about.rs"]
pub mod pages_about;

#[path = "../src/pages/test.rs"]
pub mod pages_test;

#[path = "../src/utils.rs"]
pub mod utils;

pub mod pages {
    pub use super::pages_index as index;
    pub use super::pages_about as about;
    pub use super::pages_contact as contact;
    pub use super::pages_test as test;
}

#[cfg(target_arch = "wasm32")]
#[path = "wasm_exports.rs"]
mod wasm_exports;
