// Auto-generated by lithe-cli - do not edit manually
use wasm_bindgen::prelude::*;

#[wasm_bindgen(js_name = "f_1090703e697e515d")]
pub fn __wasm_export_f_1090703e697e515d() {
    crate::pages_index::handle_local_click();
}
#[wasm_bindgen(js_name = "f_a563c899522b1e7")]
pub fn __wasm_export_f_a563c899522b1e7() {
    crate::utils::alert_from_utils();
}
